version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jscrud:latest
    container_name: jscrud
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    environment:
      SERVICE_NAME: jscrudapp
      SERVICE_TAGS: dev
    working_dir: /app
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: people
      MYSQL_ROOT_PASSWORD: password5678
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_USER: 'appuser1'
      MYSQL_PASSWORD: 'password1234'
    networks:
      - app-network
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

networks:
  app-network:
    driver: bridge
